### ISSUE TITLE
The pipeline will rerun after click select in the interactive select node and then use the selected node

### ISSUE THREAD

**Issue by ElviraLL** [lquesada/ComfyUI-Interactive#3]
Hey Thanks for the work, this is exactly what I'm looking for but when I try using the node, the workflow will rerun instead of continue. I'm using flux model generate 4 images and try using `Get Images From Batch Indexed in KJNode` and `Interactive Selector` to select an image that I want for the next step.

Please help

**Comment by lquesada** [comment]
hi,

I've seen this happen sometimes and it's triggered by nodes that do not report a correct IS_CHANGED status, which forces a rerun every time the workflow is enqueued. You could try removing nodes from your workflow until you identify which one doesn't report it well.

See the "Best Practices" section for an example: Custom-Scripts "String Function" node - this node seems to have an issue when showing the concatenated text that makes it necessary to retrigger execution of some nodes. This slows down interactive workflows. Instead, use the "String Append" node included in this repository.

**Comment by lquesada** [comment]
please keep me posted if you were manage to fix it and what node caused it, so I can document it!

**Comment by ImagineerNL** [comment]
Found a possible reason behind this;
For example; KSampler has a field for its seed named 'control after generate' . If you set that to 'randomize', that field always changes after that node is run.

![Image](https://github.com/user-attachments/assets/630572e5-15f1-433b-a117-03765da7292b)

This can be mitigated by using the 'Interactive Seed' node to fill the seed.

The issue is probably valid for any node that has a 'randomize'
